- name: Clone private Git repository with token
  git:
    repo: "https://{{ github_token }}@github.com/HienLeWw/Ansible_WebApp_Deployment_Project.git"
    dest: /var/www/html/blog-app
    clone: yes
  vars:
    github_token: "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"
        
- name: Clean npm cache
  command: npm cache clean --force
  args:
    chdir: /var/www/html/blog-app

- name: Remove existing node_modules directory
  file:
    path: /var/www/html/blog-app/node_modules
    state: absent

- name: Install project dependencies
  command: npm install
  args:
    chdir: /var/www/html/blog-app
        
- name: Install mongo-tools
  apt:
    name: mongo-tools
    state: present
        
- name: Import Users data
  shell: mongoimport --uri mongodb://127.0.0.1:27017/blog_app --collection users --file /var/www/html/blog-app/db/mernblog.users.json --jsonArray
      
- name: Import Posts data
  shell: mongoimport --uri mongodb://127.0.0.1:27017/blog_app --collection posts --file /var/www/html/blog-app/db/mernblog.posts.json --jsonArray
      
- name: Import Comments data
  shell: mongoimport --uri mongodb://127.0.0.1:27017/blog_app --collection comments --file /var/www/html/blog-app/db/mernblog.comments.json --jsonArray
      
        
